### ISSUE TITLE
Trees

### ISSUE THREAD

**Issue by dequis** [GlowstoneMC/Glowstone-Legacy#101]
> 01:00 <+SpaceManiac> The trees is a bug caused by a change in how biomes are reported a while back

**Comment by SpaceManiac** [comment]
For background, the current world gen only places trees in biomes which are foresty. Somewhere along the line, probably while improving GlowChunk, getBiome in GlowWorld was changed to return actual data (which is all 0 for Ocean) rather than a constant Hell/Sky/Forest based on environment. The world generator should either be changed to ignore biomes (easiest way to just get trees back) or fixed to actually set the biomes it's checking (more complicated, see #76).

**Comment by turt2live** [comment]
For the record: The current generator doesn't have trees.

**Comment by dequis** [comment]
So, change this from bug to feature?

**Comment by dequis** [comment]
:heart:
