### ISSUE TITLE
Shutdown bug

### ISSUE THREAD

**Issue by grzegorz2047** [GlowstoneMC/Glowstone-Legacy#157]
Server doesn't shutdown properly when I use stop command. I have some plugins which work flawless on Bukkit but here bugs.
Here is stackprint when server is shutting down:
http://wklej.to/h9inV
Also one of my primary plugins had problem with PlayerLoginEvent.
http://wklej.to/eOzom
and java class where stacktrace reference is here:
https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java
LINE where null is thrown IS: 
final Player player = event.getPlayer();

Other plugin had problem with connection to sqlite server, but probably some paths here are differrent or something(if it's implemented at all xd):
http://wklej.to/A8Bls
It throws probably ClassNotFoundException in this code:

try {
            Class.forName(org.sqlite.JDBC).newInstance();
            con = DriverManager.getConnection(org.sqlite.JDBC);
            log.info("[SQLite] Connection success!");
            createTables();
        } catch(ClassNotFoundException ex) {
            Guilds.getLogger().severe("[SQLite] Could not connect to SQLite: Could not load driver " + org.sqlite.JDBC + " to SQLite database!");
        } catch(InstantiationException ex) {
            ex.printStackTrace();
        } catch(IllegalAccessException ex) {
            log.info("[SQLite] Could not connect to SQLite: Permission error: " + ex.getMessage());
            ex.printStackTrace();
        } catch(SQLException ex) {
            ex.printStackTrace();
        }
So that's basicly all what is not working at the beggining.

**Comment by SpaceManiac** [comment]
> Server doesn't shutdown properly when I use stop command. I have some plugins which work flawless on Bukkit but here bugs.
> Here is stackprint when server is shutting down:
> http://wklej.to/h9inV

I will see if I can figure out how to extract any more information.

> and java class where stacktrace reference is here:
> https://github.com/Xephi/AuthMeReloaded/blob/master/src/main/java/fr/xephi/authme/listener/AuthMePlayerListener.java
> LINE where null is thrown IS:
> final Player player = event.getPlayer();

Are you sure this is the correct version? The code could have changed since the release you downloaded, causing a line number mismatch. Assuming AuthMe 3.4, the line is `String code = plugin.getCountryCode(event.getAddress().getHostAddress());` which at least makes sense as something possible for an error to occur on.

> Other plugin had problem with connection to sqlite server,

The missing MySQL/Sqlite drivers are being worked on, see #143.

**Comment by grzegorz2047** [comment]
Thanks for quick response. :)
About AuthMe I'm not quite sure what exacly caused problem and mindless gave you this code , but I think you correctly found what causes this error. 
About shut downing, i figured out that Essentials  vDev2.13.152 causing this problem.
I will check newest dev version if problem will still ocurr.
The newest version also causing shutdown break.
Here is full output:
http://wklej.to/hfWOl

**Comment by turt2live** [comment]
Shutdown problem ticket: #179 

As for the startup error on AuthMe, the code has changed yet again since then. Current line is `final Player player = event.getPlayer();` which shouldn't cause any issues. Are you able to provide more information on this (I personally have a plugin that fails due to scoreboards not working, but that's a different issue)?

**Comment by turt2live** [comment]
Seeing as this has become a support ticket and has been inactive for several months now, I'm closing this. @grzegorz2047 if you still have issues, please create a post on our [forums](https://forums.glowstone.net/)
