### ISSUE TITLE
Missing outer layer of skin

### ISSUE THREAD

**Issue by ZachBora** [GlowstoneMC/Glowstone-Legacy#162]
In vanilla 1.8 I can see my helmet (outer skin layer of head). In glowstone I cannot see it.
This isn't helmet from new outer layer thing, I had it before.

**Comment by SpaceManiac** [comment]
To fix this, `ClientSettingsHandler` needs to save the data it receives and properly convey the `skinFlags` of each player entity to the other players (I'm not sure how this is done in the protocol).

Fixing this will also fix ability to toggle cape (broken since ages) and toggle other skin overlay parts (like original ticket, added in 1.8).

**Comment by Aaron1011** [comment]
I've updated wiki.vg with the meaning of `skinFlags`: http://wiki.vg/Protocol#Client_Settings

I'm still not sure what the server does with them
