### ISSUE TITLE
Creating a new website.

### ISSUE THREAD

**Issue by qckcat** [GlowstoneMC/Glowstone-Legacy#170]
I can start working on (and hosting most likely) a new website for Glowstone.

Including one of my copies of XenForo.

I was just asking your permission before I started on anything.

**Comment by gdude2002** [comment]
Yes! We need this!

^ My vote.

**Comment by TomYaMee** [comment]
+1

**Comment by samis** [comment]
+1

**Comment by mariusglauer** [comment]
Also it would be nice to remove the www subdomain in the future!
See http://no-www.org/

**Comment by Grinch** [comment]
A bit premature to start a forum/proper website isn't it? Plus, if I was @SpaceManiac I'd like to have control over something that big associated with my project.

**Comment by Jckf** [comment]
http://www.yes-www.org/

**Comment by lukespragg** [comment]
Spot on @Grinch.

**Comment by qckcat** [comment]
@Grinch its never to early to get some sort of formality, community, and support.

Im just offering what I can to help the project. :)

**Comment by lukespragg** [comment]
This early on though, you'd more be opening a forum that is just going to split the development discussions into multiple locations. GitHub issues works good for me now, and preferred.

**Comment by se1by** [comment]
I think a new website can't hurt, but it's a bit early for a forum. It'd get spammed with "feature xy isn't working!" which we got github issues for.

**Comment by gdude2002** [comment]
A forum might be better for Glowstone-related discussion though as it would be given a permanent home - one that isn't IRC logs.

I don't think it's anything some decent moderation can't solve.

**Comment by zml2008** [comment]
Really the most website that Glowstone could use at the moment would be something with gh-pages, just a simple few pages to host more information than might be good to put in the README.

**Comment by Ribesg** [comment]
Anyway, nothing's wrong doing it, even if it's to let the forum itself closed and just use announcements and other various things. If people can actually work on it yet, it will be at least ready the day Glowstone is ready.

**Comment by ZachBora** [comment]
Glowstone needs a doxygen!

**Comment by lukespragg** [comment]
Doxygen is just generated docs, which you could generate yourself.

**Comment by Seshpenguin** [comment]
Where are you planning to host the site? (I could host it)

**Comment by ZachBora** [comment]
@lukespragg But it needs to be public.

**Comment by lukespragg** [comment]
I think most prefer Javadocs, but someone could setup both to be generated. Course if you go with Doxygen, might as well go with Sphnix too? ;)

@Seshpenguin, I'd suggest using GitHub for now, with both discussion and the site. If the site is hosted with GitHub, others can easily contribute toward it. It's fairly simple to setup too.

**Comment by gdude2002** [comment]
I much prefer javadocs, and getting gradle to generate them is piss, really.

**Comment by qckcat** [comment]
I would ask @SpaceManiac what he would prefer, I can host it for free. Or I can let him host it elsewhere.

If a forum isn't needed, I would still like to develop a better site in general. :)

**Comment by lukespragg** [comment]
Biggest issue is things being in the hands of randoms @thegarfish. Hosting it under his control via something such as GitHub seems like the best solution for all, as it remains in his control, and others can submit/contribute/PR toward the site.

**Comment by qckcat** [comment]
I wasn't planning on giving it to a random, I was going to see what he wanted to do. :)

Whomever host is, I can can work on a website as my development skillset lays in web development.

I also had a spare copy of xenforo that I am offering aswell.

**Comment by lukespragg** [comment]
I'd prefer NodeBB over XenForo personally. XenForo has been a bit overused in the community, with all the same cookiecutter themes. Bonus is that NodeBB is free forever without yearly upgrade costs.

**Comment by qckcat** [comment]
As I stated, I wasn't pushing for just them forum end of things.

**Comment by lukespragg** [comment]
No worries, just putting up options. ;)

**Comment by qckcat** [comment]
Good point, i'll check out NodeBB. :)

I just wanted to start a new web project, and I thought this would be a good project.

**Comment by SpaceManiac** [comment]
I'll consider plans regarding a more full forums (and look at the software choices). Been lots of offers for hosting so I'll consider that too.

In the meantime, contributions to `gh-pages` branch or wiki (or other WIP whatevers) are welcome.

**Comment by gdude2002** [comment]
@ZachBora wanted docs?

http://cherry.gserv.me/docs/net.glowstone/

**Comment by barneyputman** [comment]
I can give you the domain i own this ^^ http://glowstone.io/

**Comment by Ribesg** [comment]
@ksocially make it redirect to http://www.glowstone.net/ and... wondering why you actually invested in that but... anyway

**Comment by ZachBora** [comment]
@gdude2002 I wanted a doxygen :(

**Comment by Ribesg** [comment]
JavaDucks masterace

**Comment by se1by** [comment]
@ZachBora but normal javadocs are way better :o

**Comment by ZachBora** [comment]
@se1by I don't know why people prefer javadocs, all the reasons I use these docs for aren't present or as good in javadocs.
- I use doxygen to search
- I can easily look at the class source without going over to the repository
- You have a graphic of the class hierarchy (in javadocs all you see is the parent, not brother classes)
- On the left I can see what other classes are in the current package easily

**Comment by turt2live** [comment]
@ZachBora all of that is possible with JavaDocs, besides search. 

Edit: @ksocially : Why would you purchase that domain? You'll likely want to talk to @SpaceManiac now about transferring ownership.

**Comment by se1by** [comment]
@ZachBora 
Most of the time I just want to see what method x does, so javadoc is better for me as it's more clear imho.
Maybe we can have both (like javadoc at jd.glowstone.net and doxygen at dg.glowstone.net)?

**Comment by turt2live** [comment]
@se1by or do the same thing as Bukkit...

jd.glowstone.net/jd
jd.glowstone.net/doxygen

**Comment by se1by** [comment]
@turt2live nah, I want to be directly at the docs, without an additional "/jd" :P

**Comment by gdude2002** [comment]
If someone wants to give me a crash course in doxygen then I'll set it up as well.

**Comment by ZachBora** [comment]
@turt2live Look at the inheritance diagram here : http://jd.bukkit.org/dev/doxygen/de/dd5/interfaceorg_1_1bukkit_1_1entity_1_1Entity.html

Now look at the known subclasses on here :
http://jd.bukkit.org/dev/apidocs/org/bukkit/entity/Entity.html

doxygen presentation much much more useful.

**Comment by gdude2002** [comment]
@ZachBora That means you, fyi. Javadocs are done with `gradle doc`, what's the best way to generate doxygen docs?

**Comment by turt2live** [comment]
@ZachBora to be honest I don't like doxygen because of how it looks. No other reasons. I was just pointing out that your features are there in javadoc. 

Ideally, both would be supplied.

**Comment by Ribesg** [comment]
@turt2live and also URLs, ewww Doxygen URLs!

**Comment by barneyputman** [comment]
i reserved it because i heard that someone could register it and it looks good for the plugins list or forum. :P and i have an hosting i will offer you the team want, cloudflare premium anything i want to make this the "better bukkit"

**Comment by HenrySlawniak** [comment]
I would like to throw discourse.org into the list of possible forums. :D

**Comment by navarr** [comment]
Right now is a poor time to focus on bikeshedding problems such as a website.  Is a forum even necessary for this project?

Let's focus on getting shit done first, guys.

**Comment by Ribesg** [comment]
@navarr I understand that there are people that aren't able to contribute to the Glowstone project itself, because they're more into Web things, that's why such things are not guaranteed to slow down the actual Glowstone development at all. @SpaceManiac should still have control over everything and the final word on what we should do about this.

I really don't like Discourse and NodeBB. Using Xenforo will help Bukkit users a lot, I think.

**Comment by ZachBora** [comment]
@turt2live and I don't like how javadocs look

@gdude2002 I'll check how doxygen works

**Comment by barneyputman** [comment]
because i see future on the glowstone project and this is my donation c:

**Comment by qckcat** [comment]
I'll start my version of the site today. :) Expect me to post pictures soon.

As for why we need a website, as the project grows.. The community needs to be more together, considering my main talent is webdev, I wanted to use my skills to help the project.

I'll also allow group collaboration, get ideas, etc. SpaceManiac will still have control over everything, I'll just help build it.

**Comment by mastercoms** [comment]
@thegarfish I can help you with the website.

**Comment by gdude2002** [comment]
I'd love to see how this goes - feel free to ask me here or on IRC (as g) about stuff, I'd be happy to help out

**Comment by SpaceManiac** [comment]
See #291 for an effort to improve the Glowstone front page. Anything more complicated is pending a choice of software.

**Comment by turt2live** [comment]
(added support label as this does not directly affect the code)

**Comment by TnTBass** [comment]
Might be a good idea to setup some forums.  Doesn't have to be extensive, just simply a couple sections: News, Help, Discussion and Offtopic.  The forums can always be expanded later when there is more need for more forum sections.

This is of course a selfish request - so I can find out information about Glowstone without asking in IRC, or digging through github (which I don't spend much time on).

**Comment by daboross** [comment]
Yay for the bikeshed effect

**Comment by tmazeika** [comment]
:+1: 

And what drtshock said
v v v v v

**Comment by drtshock** [comment]
pls no discourse

**Comment by bendem** [comment]
> pls no discourse

yes, please no!

**Comment by dequis** [comment]
> This is of course a selfish request - so I can find out information about Glowstone without asking in IRC, or digging through github (which I don't spend much time on).

Not too selfish, I agree it must be hard to follow for those who don't IRC 24/7 or watch the github repo. In fact I'm surprised the contributors can keep up with our bullshit so well.

> pls no discourse

Suggest alternatives

**Comment by drtshock** [comment]
Xenforo ;D
I'd be happy to assist in any capacity the setup of xenforo.

**Comment by gdude2002** [comment]
@dequis suggested that I be the one to set up/host the forum, which I'm pretty happy to do. I already know how Xenforo works as well, so I'm totally happy to work with that, although frankly I'd be happy with anything that isn't Discourse.

**Comment by SpaceManiac** [comment]
@drtshock @bendem What are your specific complaints with Discourse (and how does Xenforo do those things better)?

**Comment by gdude2002** [comment]
The general consensus on Discourse is that it's not really suitable for any kind of persistent conversation. There are no subforums, instead you get one giant listing of topics and a searchable tag cloud.

Moreover, it's a very new piece of software, and the security implications of using it haven't really been discovered yet, early adopters be damned.

**Comment by Ribesg** [comment]
Also, every Discourse website is strictly the same.

I've used NodeBB for some time now, and while it's still in early development (I would say it's more a Beta than an Alpha), you can already _drastically_ customize it. Subcategories where just added.

[Here](http://battle-realms.fr/) you can see my ugly theme where I have big categories with subcategories (It's a work in progress but you get the idea).

If you want a kinda-frozen forum design that works, I don't see why we would use Discourse while Xenforo is here.

**Comment by gdude2002** [comment]
@Ribesg I like that it asked to show desktop notifications when I loaded it up; what are those for exactly?

**Comment by Ribesg** [comment]
Ehm... Showing desktop notifications? Like any notifications you have on any forum, but on the desktop :P

It's quite cool when you're in IntelliJ IDEA doing stuff and somebody answers your post, stuff like that. Aaaaaaaaaaaaand you can refuse, there's still the "integrated" notification thing.

**Comment by gdude2002** [comment]
In general I do like the look and idea of NodeBB, I think some people here are against it though; let's see what people think

**Comment by dequis** [comment]
Can you make NodeBB look like xenforo? If so, sold. (Only half-kidding there - we need money for xenforo)

**Comment by Ribesg** [comment]
You can make it look like Xenforo yes. There's a quite powerful theming system.

For example if you're not into standard forums, look at [Convoe](https://convoe.com/). It's the most polished NodeBB forum I know.

**Comment by bendem** [comment]
> @gdude2002: Moreover, it's a very new piece of software, and the security implications of using it haven't really been discovered yet, early adopters be damned.

_@Ribesg: used NodeBB for some time now, and while it's still in early development (I would say it's more a Beta than an Alpha), you can already drastically customize it. Subcategories where just added._

I'm not sure NodeBB could be a candidate considering @gdude2002's argument.

**Comment by gdude2002** [comment]
@bendem does have a point actually.. I do like NodeBB but maybe we should use something more tested for now.

**Comment by greatman** [comment]
@turt2live was able to break nodebb several ways if I remember when we
tested that solution some months earlier.

**Comment by Ribesg** [comment]
@greatman yeah it depends on which version you tried, every x.x.0 version is full of bugs. They basically add new features on major updates and fix a shiton of bugs on minor updates, adding little feature from time to time.

I don't consider NodeBB ready for anything critical. Is Glowstone critical (yet)?

My second choice would be Xenforo. Somebody offered a license some time ago iirc

**Comment by gdude2002** [comment]
@Ribesg @greatman - @drtshock offered to throw us a license if we can all agree on Xenforo

**Comment by navarr** [comment]
I believe I said it earlier, and I feel the need to say it again.

I would absolutely not recommend Xenforo.  Xenforo is built on very old outdated frameworks (Zend Framework 1), did not have good password hashing the last time I checked, and will be very difficult to put anything custom on it if desired.

I think we need to do a few things here:
- Move this ticket to a different repository
- Decide what features are necessary for the Glowstone website
- Talk about potential software after we know what we want to do with the website

Key points being 2 and 3.  Deciding on software before knowing what exactly the use case is is absurd.

**Comment by gdude2002** [comment]
> Xenforo is built on very old outdated frameworks (Zend Framework 1)

Zend itself was always pretty good, but I guess it would be nice if they updated, yeah. Also, PHP.

> did not have good password hashing the last time I checked

When? Got any links for us?

> will be very difficult to put anything custom on it

I can confirm this one at least, Xen is a real pain in the ass to extend

---

> Move this ticket to a different repository

Which one?

> Decide what features are necessary for the Glowstone website

We're not talking about the entire website at this point, but most of it will most likely require the same kind of things Bukkit did, sans all the Curse fuckery. It doesn't have to be permanent, as far as I've heard, but we need _something_ to work with.

> Talk about potential software after we know what we want to do with the website

I think that's what we're doing here. Any alternatives to suggest? \o/

**Comment by navarr** [comment]
@gdude2002 I haven't seen a feature list.  I see that people want some discussion, but maybe not because users will complain about features, but maybe yes for announcements.

I don't see any hard coded list of necessary features.  And it's a mistake to dive head-first into software before then, because a) it might be difficult to do what you want to within that software and b) once you've started using it nobody will want to go through the effort of a transition.

It's very important to get down your needs and make sure the software you choose will fulfill them.

**Comment by gdude2002** [comment]
@navarr I understand that, but as I understand it we need somewhere to discuss stuff that's at least semi-permanent that isn't like.. GitHub.

Also, edited my ticket above a few times, sorry.

**Comment by dequis** [comment]
> I don't see any hard coded list of necessary features.

We need:
- A forum
- That doesn't suck.
- That isn't github
- Where users who don't IRC can post support questions
- Where other non-IRC discussion can happen

**Comment by navarr** [comment]
@dequis @gdude2002 So the only requirements for the Glowstone website is that it is a forum.  For the sake of being a forum?

There are no other requirements.  Nothing else ever has to be done on this website.  Ever.

**Comment by dequis** [comment]
We already have a nice website - http://www.glowstone.net/ - all we're missing now is a forum, and that's what this ticket is about currently (note that it was created two months ago)

**Comment by Etherealflux** [comment]
@navarr I do not see how our choice of forum would have anything to do with the rest of the website. The point is to get a nice little discussion board up so that people can discuss Glowstone- nothing more.

**Comment by gdude2002** [comment]
I think we should just let @SpaceManiac decide at this point. We shouldn't make the same mistake Sponge keeps making (making everything a lengthy community vote), and we should really get a move on with this anyway.

According to [this poll which has no guarantee of choice whatsoever](http://strawpoll.me/3009708/r), Xenforo seems to be popular. (Thanks @Ribesg!)

EDIT: added an image because strawpoll is so easy to break

![](http://i.imgur.com/u2r5P0S.png)

**Comment by PaulBGD** [comment]
If (and only if) we use NodeBB, I'd be willing to create a theme for free.

**Comment by SpaceManiac** [comment]
How easy does XenForo make it to disable some of the wacky social features (likes, trophy points, posting on profile pages)?

> There are no subforums, instead you get one giant listing of topics and a searchable tag cloud.

The [Sponge forums frontpage](https://forums.spongepowered.org/) is the categories view, which is fairly conventional. I believe, though I need to check, that you can enforce topics having exactly one category.

**Comment by gdude2002** [comment]
> How easy does XenForo make it to disable some of the wacky social features?

Pretty easy, just revoke permissions or don't make any trophies. I'm sure some of it can be disabled directly as well. Although, I dunno why you'd disable those in the first place, really.

**Comment by bendem** [comment]
I'd propose eXo plateform, a java open source discussion plateform. It looks nice and seem to have a lot of neat features. It's also very mature (first commit is from Mars 17, 2007)
I'll test it when I get home.

https://github.com/exoplatform
http://community.exoplatform.com/portal/intranet/open-source-projects

**Comment by gdude2002** [comment]
@bendem You mentioned a community edition before, but I can't seem to see anything like that, at least not anything that I don't need an account for. How hard is this to set up?

**Comment by bendem** [comment]
![](http://i.bendem.be/2014/11/18_09-54-21.png)

**Comment by gdude2002** [comment]
@bendem Ah, okay, didn't see it.

Well, it does look pretty nice, but atm Xenforo is winning out. Have you used this? What does it give us that's better than xenforo but doesn't cause the feature creep that @SpaceManiac is trying to avoid?

**Comment by bendem** [comment]
_"I'll test it when I get home."_ To see if it's worth investigating further

**Comment by gdude2002** [comment]
More coffee required! Okay, thanks, lol, sorry.

**Comment by maxov** [comment]
I highly recommend [esotalk](http://esotalk.org). Clean, FOSS, simple. I really like how their [community](http://esotalk.org/forum) looks, although some people are against the "channels" idea. It is also written in php, so keep that in mind.

**Comment by gdude2002** [comment]
I've been doing some testing. Here are my results so far.

---

**NodeBB**

Looks nice. Couldn't get it to work at all, though. Forum was stuck in readonly mode with zero errors (readonly mode is when the client JS breaks for some reason). I got it to work for one settings change in Firefox, and it went back to not working.

---

**eXo Platform**

Oh god, where do I begin?

This thing is so unbelievably corporate. I took some screenshots to show what I meant.

![](http://i.imgur.com/hXCyCbg.png)
![](http://i.imgur.com/4xC8OI8.png)

Not a frickin' clue how this thing is supposed to work. I did manage to get to the forums and set up one forum and post, though.

![](http://i.imgur.com/VjbnzDy.png)
![](http://i.imgur.com/13Zt5WK.png)
![](http://i.imgur.com/WgdguMw.png)

It looks terrible and it feels kind of unusable. Also, note the address bar in these three - it's the same. If you go back and then forward, you do not get to the page you were just at.

**Comment by navarr** [comment]
Here are some more thoughts from me, which everyone is already tired of reading:
- Xenforo is over-complicated and burdensome.  It seems like way more than the project needs.  If there are plans for future development it will also be a burden. Xenforo should be used as a total replacement to the current website, and then have fun with it's burdensome theme system and extending it ever (like Spigot and Bukkit did)
- NodeBB is _really_ cool.  It's built on top of new technology and stands alone as a forum.  It's built on top of Node.js for some neat live stuff, but JavaScript is also very fragile.  It could break at any time or have very strange bugs in multiple browsers.
- eXo looks really neat but even more complicated and burdensome than Xenforo.
- Discourse is great - the only complaints I'm reading here are people who don't like it's categorization system (which is fine - especially when the topic is as limited as "Glowstone").  It's not built on PHP so you'll have some fun times installing it.
- SMF/phpBB are simple and old.  They pretty much just do their one thing as good as they can.  phpBB is especially good with it's ACL - but probably not a desire here.

If it's a "quick we need a place to discuss because I hate github for some reason" then phpBB, Discourse, or NodeBB are all heavily recommended options.  They all stand alone and try to do their one thing really well.  They all also have the benefit of being FREE and OPEN SOURCE (which Xenforo at least does not).

Personally, I have yet to understand why Github isn't good enough for a development community, especially since issues are self-contained.

**Comment by turt2live** [comment]
For the record, xenforo is my vote because it is familiar to most users of
the project.

sent from mobile

**Comment by drtshock** [comment]
@navarr how is xenforo over complicated and burdensome? It's easy to use and a lot of people are familiar with it already. It didn't take me long to learn how to administrate, moderate, and use it. Your comments makes me think that you're attempting to portray objective reasons but they're almost all subjective.

**Comment by navarr** [comment]
@drtshock Xenforo is immensely over complicated for wanting "just a forum."  It's ACL system is a complicated mess, it's node tree cumbersome - the best part of Xenforo it's its plugin base, and even that requires you to do much more than a plugin system should to install any. (I use Xenforo constantly as an administrative user & developer, which is why I'm so particularly pointed against it)

These are the reasons I'm against Xenforo.  Even if it's familiar we're talking about "just a forum" at which point any forum software that doesn't redesign how it works (so the exclusions are NodeBB and Discourse) are familiar to users.

**Comment by mastercoms** [comment]
+1 for esotalk

**Comment by gdude2002** [comment]
I think what was meant is that there are people here that are used to
working with it from an administrative point of view as well.

Xenforo is not that complicated at all, not unless you make it so. As for
plugins, there is a very good plugin installer out there, I've been using
it for over a year now.

Discourse and Esotalk or whatever it is are out because they entirely
redefine what a forum is. Exoplatform is out because it's just.. Not a
forum and way too much. NodeBB is out because I couldn't get it to work.
SMF is out because of security considerations. Vbulletin is out as it's
widely known to be bad and broken. IP.B is generally disliked.

So that leaves us with Xenforo, PHPBB, and.. What?

**Comment by mastercoms** [comment]
If we are going with a normal forum, I vote for Xenforo.
For a reimagined forum, esotalk.

**Comment by dequis** [comment]
I just checked what the [arch linux forums](https://bbs.archlinux.org/) use, it's this: http://fluxbb.org/

Fits a 'minimalist' definition of normal forum

**Comment by gdude2002** [comment]
@dequis Decided to try FluxBB. http://gs.gserv.me

Don't really like. The theme is meh, but I particularly dislike that you get sent to a redirect page with literally everything you do. That really bugs me and shouldn't be a thing.

**Comment by dequis** [comment]
> I particularly dislike that you get sent to a redirect page with literally everything you do. That really bugs me and shouldn't be a thing

Agree. There's a setting for that in the admin, but it says it's not recommended for whatever reason, probably support for ancient browsers.

> The theme is meh

Fixable problem, tbh. There's a few decent ones on their site, but eh. I'm willing to spend some time adapting a decent theme if this turns out to be the biggest issue.

My main vote still goes for xenforo, but this is a cheap (free) alternative, and seems to have a decent history of vulnerabilities in its lifetime.

**Comment by gdude2002** [comment]
> There's a setting for that in the admin

Where? It's kind of hard to traverse, most of the settings are thrown into the same place

**Comment by dequis** [comment]
> Where?

"Redirect time" - "Number of seconds to wait when redirecting. If set to 0, no redirect page will be displayed"

> a decent history of vulnerabilities in its lifetime.

Was asked on irc, so, to clarify that last sentence, i meant that, in comparison to other projects, it has had few vulnerabilities disclosed during its lifetime. Two CVEs assigned (but unused, was [one XSS](http://www.openwall.com/lists/oss-security/2010/10/08/8) and one [minor issue with reverse proxies](http://www.openwall.com/lists/oss-security/2011/10/10/9)) and [one bugtraq entry for XSS](http://www.securityfocus.com/bid/58413).

[Compare and contrast](http://www.cvedetails.com/product/2635/Phpbb-Phpbb.html?vendor_id=1529)

Needless to say, this is all issues fixed in the latest version. It's about how often they come up.

**Comment by gdude2002** [comment]
@SpaceManiac: so far I haven't managed to find an alternative to Xenforo that I find viable or satisfactory. Are you able to come up with another suggestion, or to make a decision?

**Comment by SpaceManiac** [comment]
I'm going to take some time to poke at Discourse and see if I can configure it to my liking wrt to the category system, since I really like Markdown for posts and things seem to be working for the Sponge forums so far. If there's problems with Discourse, I'll poke at the more-traditional NodeBB instead, and if both of these fail I'll cede victory to XenForo.

**Comment by SpaceManiac** [comment]
@greatman has been so kind as to provide a Discourse test instance, [available here](http://discourse.greatmancode.com/). Would love feedback on the category structure and actual navigability of the site so far.

As a note, the lack of a Glowstone/Development category is due to a preference for the majority of development discussion to occur on GitHub rather than on the forums.

**Comment by gdude2002** [comment]
If we're going to use discourse then I'm just not going to use the forum; I spent enough time wrestling with the software when the Stonehearth community decided to use it. 

NodeBB has already been tested, it doesn't function if someone has JavaScript disabled and I couldn't get the websockets to work while following the official documentation to the letter, leaving it stuck in read-only mode. I checked out the Discourse link above and it also appears to rely heavily on JS - someone should test it without, as we can't not support those that do disable JS or are on mobile devices.

EDIT: Also, I'll point out now that you're very much seeing it from a developer perspective. As someone that started their Internet journey by spending years in various forums, normal people don't care about or want Markdown or odd alternative category views - they want something easy, maybe with a WYSIWYG editor and the bbcode that's familiar to them from all the other forums they've used. 

Also, pinging @SpaceManiac so you actually see this.

**Comment by Ribesg** [comment]
> we can't not support those that do disable JS

I don't agree with that. People disabling JS in 2014 just don't want to browse the Internet. NodeBB and Discourse are designed to fully support mobiles.
You want to support **every single** device? There is _absolutely no other option_ than a mailing list then.

> normal people don't care about or want Markdown or odd alternative category views - they want something easy, maybe with a WYSIWYG editor

NodeBB has Markdown _AND_ WYSIWYG.

**Comment by gdude2002** [comment]
> People disabling JS in 2014 just don't want to browse the Internet

So, blind people, people who disable JS on sites they haven't been to before for security reasons, people behind corporate firewalls that block JS for security reasons, people that use Tor, people on slower mobile devices, and people that simply disable JS because sites have a metric ton of JS for advertising/other trivial purposes that can slow a browser to hell.. Should all not be allowed to use our forums?

> NodeBB has Markdown AND WYSIWYG.

NodeBB is great, but it doesn't work for me. It really don't matter what it has if it doesn't work. I would agree that it has the best way to learn Markdown though, but that assumes people want to learn Markdown. Another problem is that it requires websockets to do basically anything - you stated on IRC that it looks like things you type are streamed to the server using one, where I assume it'd be compiled to Markdown and shown in the preview pane.

This seems.. bad. I wouldn't want this in production, especially if we even get close to the scale of Bukkit. Automatic DDoS, eh?

---

```
[09:27] <Ribesg> MD is simpler than BBCode, nuf said
```

Missing the point.

We're looking at a community containing users that match at least a couple of the following points each...
- Is young and doesn't want to work with "hieroglyphs" or simply can't understand them
- Is old and doesn't want to learn something new to format posts
- Is computer-illiterate and just wants to put some emphasis in their plugin report
- Cares enough to report a problem or share their opinion, but not enough to learn a new markup format to do so
- **Is coming from the Bukkit site**, which they may have spent a great deal of time getting used to (we are a Bukkit replacement after all)
- Has been using traditional forums for years and is used to or expects a system similar to the way forums have naturally worked for a long time

Markdown is simpler than BBCode when you're doing the things that Markdown can do. What Markdown can't do is be extended while keeping the spec the same. One of the most-used features on many forum software suites is the ability to define custom BBCode - for example, the Bukkit forum had custom BBCodes to nicely embed plugins pages from DBO. How would you do anything like this with Markdown?

I hope this has made the points clearer for you, @Ribesg

**Comment by Jckf** [comment]
NodeBB isn't ready for production use anyway, so there is no point in looking at it unless the plan is to not have a forum ready for quite some time.

**Comment by SpaceManiac** [comment]
Discourse supports mixing Markdown and a BBCode subset (at least B, I, and IMG, probably others - the ones most commonly used). It also uses BBCode for syntax extensions (e.g. the `[quote]` tag used to quote other posts in the thread with a link). Plugins can add custom BBCode this way.

Instead of a WYSYWIG it uses a preview pane, and has buttons to insert markup for `quote post, B, I | link, blockquote, code, upload | ol, ul, heading, hr` into the editor.

It sounds like NodeBB is out as an option then given its extreme reliance on JS and apparent unfinishedness.

**Comment by ZephireNZ** [comment]
I honestly really like Discourse. It seems a lot cleaner and modern than most of the 'classic' forum software. Also, if Sponge does become the de facto server, people will likely get used to Discourse's different ways of doing things, so it's won't be as much of a leap for people to then use our forum.

**Comment by gdude2002** [comment]
Discourse is unusable without JS, apparently.

**Comment by navarr** [comment]
Any modern web application is unusable without JavaScript. While being able
to fall back is nice, the vast majority of the Glowstone target audience
has and uses JavaScript.

**Comment by gdude2002** [comment]
We've had this discussion already, you should sit on IRC sometime :P

**Comment by PaulBGD** [comment]
@navarr Did you say NodeBB would be bad because it uses JavaScript and not all browsers have compatibility.. You do realize it's ran server side, right?

**Comment by turt2live** [comment]
Uhh.. since when is client-side javascript run server-side?

**Comment by dequis** [comment]
> client-side javascript run server-side

Well there's https://github.com/mhart/react-server-example

(kidding)

> Did you say NodeBB would be bad because it uses JavaScript and not all browsers have compatibility

FWIW, gdude was the one who said that. See his [long comment](https://github.com/GlowstoneMC/Glowstone/issues/170#issuecomment-63782464) a while ago for details.

---

Also, friendly reminder that since this discussion is going nowhere, SpaceManiac in charge of the final decision on what to use, and we just have to accept his choice and realize that in the end it doesn't really matter _that_ much if he picks shitty forum A or shitty forum B.

Just don't get mad at him if he picks something you dislike. Be polite, etc.

**Comment by PaulBGD** [comment]
@dequis I was referring to when he said:
"NodeBB is really cool. It's built on top of new technology and stands alone as a forum. It's built on top of Node.js for some neat live stuff, but JavaScript is also very fragile. It could break at any time or have very strange bugs in multiple browser"

**Comment by gdude2002** [comment]
@dequis is unfortunately correct. @SpaceManiac gets the final say here. I think, then, that it may be best to lock this ticket; we already have a metric ton of feedback and suggestions, all we can do now is wait.

**Comment by SpaceManiac** [comment]
As much as I know some people won't like it, I think I want to roll with Discourse for now. There are some valid concerns (users with JS disabled, markdown unfamiliarity [also supports bbcode], category system [customized fairly easily], moderator tools??) but they're pretty answerable and I like what I've seen of the software so far, from Sponge and from experimenting with the admin panel. I'm not married to it, though; if there proves to in fact be some insurmountable obstacle making Discourse simply the wrong choice, I'm willing to switch to XenForo instead.

**Comment by gdude2002** [comment]
@SpaceManiac Alright, I'll work on deploying when I get home. (Wonder why my email didn't go through)

Do we have a mailgun for the Glowstone domain? What domain are we using? If we don't have a mailgun, please set one up so some poor soul doesn't have to set up postfix

**Comment by gdude2002** [comment]
There is a forum live at https://gs.gserv.me which will be moved to https://forums.glowstone.net when SM has time to update the DNS. Everything will function fine until then, but you may have to rewrite some of the links yourself (such as those in emails for example)

**Comment by SpaceManiac** [comment]
Going ahead and considering this closed since the forum is now live at https://forums.glowstone.net/

Further general discussion about web issues can take place either here (if it's more of an issue trackery type problem) or on the forum (for general concerns or support).

**Comment by gdude2002** [comment]
So now that [our forums are set up](https://forums.glowstone.net), does anyone have any feedback? Feel free to respond to this ticket, or to [dx's thread](https://forums.glowstone.net/t/suggestions-for-the-forum/73).

**Comment by barneyputman** [comment]
why do not use this domain that i donated to you, it looked way more cool xD
glowstone.io

**Comment by barneyputman** [comment]
for the forums XD

**Comment by PaulBGD** [comment]
CNAME it and use it yourself then.

**Comment by gdude2002** [comment]
@ksocially Because we already have a domain that everyone already knows ._.
