### ISSUE TITLE
"Rogue thread" crash when stopping server

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#179]
Hello!
When I attempt to stop the server running /stop in the console (This is on a localhost server) I get the following error and the server acts like it has crashed http://prntscr.com/4kefnx

![Crash](http://i.imgur.com/yIgUd0e.png)

**Comment by SpaceManiac** [comment]
I'd like to note that this can be caused by running CommandHelper, which does some threading things. Likely to be caused by any plugin doing weird threading. I have no idea what the actual cause is.

Note also that ShutdownMonitor fails to actually kill the errant threads and close the application... this should probably be fixed.

A fix for this should probably fix "rouge" -> "rogue" while at it.

**Comment by turt2live** [comment]
I can confirm that anything which uses the scheduler seems to cause this issue.

**Comment by mastercoms** [comment]
I'm writing some code in both the ShutdownMonitor and net.glowstone.scheduler so the scheduler can respect a shutdown.
And if a runnable for some reason does not respect scheduler's shutdown request, it will forcefully kill all leftover runnables.

**Comment by mastercoms** [comment]
Any plugins I should test with?

**Comment by ghost** [comment]
I will get my plugin list in a second

**Comment by mastercoms** [comment]
@Luke199 Alright.

**Comment by ghost** [comment]
Here you go http://prntscr.com/4kok0e

**Comment by mastercoms** [comment]
@Luke199 Thanks, I'll test it out in a moment.

**Comment by mastercoms** [comment]
Ok, #179 is not fixed by #207 yet, I'm going to have to do a lot more work with the scheduler, and rewrite some logic for the shutdownmonitor.

EDIT: With the new commit, #207 fixes #179.
