### ISSUE TITLE
Decide name of Bukkit fork and all other details

### ISSUE THREAD

**Issue by Ribesg** [GlowstoneMC/Glowstone-Legacy#221]
Things could be added to Bukkit as soon as we need them.
A lot of things that anybody could use in a Bukkit plugin are missing.

--> https://github.com/GlowstoneMC/Glowkit

**Comment by turt2live** [comment]
https://github.com/SpaceManiac/Bukkit

**Comment by Ribesg** [comment]
I mean a real fork with its own name and identity, Maven repo, and all.

**Comment by mastercoms** [comment]
I think we should leave that to Sponge or whatever. We can integrate their own API when we can.

**Comment by SpaceManiac** [comment]
I think _some_ degree of Bukkit fork is necessary. At a minimum, `enum` updates for 1.8 additions (because Glowstone relies on these to know what really exists). turt2live has suggested some old Bukkit PRs that would be worthwhile to merge - 3 formatting ones and a new API method that Glowstone already supports internally are on my radar, and many other API additions which GS can't implement yet are possibilities for the future.

Need to decide naming, maven, and versioning policies though - and it's likely pace will be very slow, only in a "maintenance" capacity - no big revolutions.

https://github.com/GlowstoneMC/Glowkit

**Comment by Ribesg** [comment]
So, name suggestions?
- GlowBukkit
- Glukkit

Should not got too far from Bukkit as it's just about maintaining, updating and adding small missing things.

**Comment by zyuiop** [comment]
We could just call it GlowstoneAPI and explain on the website it's forked from BukkitAPI 1.7-R4 so compatibility with old bukkit plugins is supported.
We could also call it Redstone, because it's the technical part of the software

**Comment by daboross** [comment]
If Bukkit is and will always be the only API supported by Glowstone, I would name it `glowstone-api` with the id `net.glowstone.glowstone-api`.

Otherwise, if Glowstone will in future support other APIs as well, I would just go with `bukkit-updates` with the id `net.glowstone.bukkit-updates`.

**Comment by JeromSar** [comment]
GlowBukkit?

**Comment by mastercoms** [comment]
Pail or GlowKit

**Comment by Ribesg** [comment]
http://strawpoll.me/2523958

**Comment by SpaceManiac** [comment]
"Glowkit" decided on as name. Maven project id whatever thing should be either `net.glowstone:bukkit` or `net.glowstone:glowkit`, thoughts?

**Comment by Postremus** [comment]
will the package name stay the same (org.bukkit.*)?

2014-09-08 20:08 GMT+02:00 Tad Hardesty notifications@github.com:

**Comment by daboross** [comment]
`net.glowstone:glowkit` would be my vote

**Comment by dequis** [comment]
Plugins compiled against bukkit will still work, right?

**Comment by daboross** [comment]
@dequis yes, unless Glowkit makes non-backwards-compatible changes, which I think is unlikely.

**Comment by SpaceManiac** [comment]
Yes. Package name will stay the same - changes made will be for maintenance purposes only.

**Comment by turt2live** [comment]
Decided upon already. See https://github.com/GlowstoneMC/Glowkit
