### ISSUE TITLE
Rare exception when 40+ clients disconnect in the same tick

### ISSUE THREAD

**Issue by turt2live** [GlowstoneMC/Glowstone-Legacy#421]
```
2014/10/12 14:29:10 [SEVERE] Error occurred while pulsing world world
java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
    at java.util.HashMap$ValueIterator.next(HashMap.java:950)
    at net.glowstone.entity.GlowPlayer.pulse(GlowPlayer.java:416)
    at net.glowstone.GlowWorld.pulse(GlowWorld.java:371)
    at net.glowstone.scheduler.WorldScheduler$WorldThread.run(WorldScheduler.java:48)
```

No other information available.

**Comment by mastercoms** [comment]
Does this happen on other server implementations?

**Comment by ghost** [comment]
GlowPlayer part of the Glowstone..

**Comment by turt2live** [comment]
I was just about to say, the exception is very Glowstone specific

**Comment by ghost** [comment]
This happens when 2 threads loop trough collection. Currently using HashMap collection that not supports multithreading. To avoid need change collection to ConcurrentHashMap.

**Comment by turt2live** [comment]
That's not necessarily a root issue fix. Someone needs to do more investigation.

**Comment by mastercoms** [comment]
@turt2live yeah, my bad, idk why I thought to say that.

**Comment by socram8888** [comment]
Well, player connections are asynchronous so you will have to either keep a list of disconnected users to remove them from the HashMap in the server's main loop and fire events, or just do as @ensirius said and use a multithreading-safe alternative.

**Comment by coelho** [comment]
The issue here is that the Netty callback MessageHandler.channelInactive(ChannelHandlerContext ctx); is called, which will then call GlowSession.onDisconnect();, then calling player.remove();

When a player is removed, we currently immediately remove them from the EntityManager, which causes a concurrent modification exception when we happen to be iterating over the EntityManager.

To fix this, it's probably a good idea to change onDisconnect to only set a boolean disconnected to true. Then on each pulse, check if the player is disconnected, and if he is, call the previous body of onDisconnect.

Switching to a ConcurrentHashMap is a bad idea as the server already has a lot of code in place to ensure that this HashMap is thread safe. It is only in this single incident that it will prove unsafe.

**Comment by turt2live** [comment]
Closing this to clean up my issues list on Github. If this is still an issue, please port it over to https://github.com/GlowstoneMC/Glowstone
