### ISSUE TITLE
Water Is Glitched Out and Will Not Replace Itself When a Block In The Water is Destroyed

### ISSUE THREAD

**Issue by yannouli** [GlowstoneMC/Glowstone-Legacy#507]
I went on my server and spawned near an ocean. I placed a sponge in the water and nothing happened. Then when I destroyed the sponge, the place where the sponge used to be was empty, the water did not flow to replace the air in the space. Please tell me how to fix this.

**Comment by turt2live** [comment]
This is due to #40.

Glowstone is not currently complete. We are working hard to get Glowstone to a fully functional server implementation, but right now there are various unimplemented features.

Many of the features we current have can be found [here](https://github.com/GlowstoneMC/Glowstone/wiki/Current-Features)
