### ISSUE TITLE
Redstone Does Not Work

### ISSUE THREAD

**Issue by yannouli** [GlowstoneMC/Glowstone-Legacy#508]
Redstone does not function at all in the game. When I placed down a lamp and a button on top of it, I pressed the button and nothing happened. I destroyed the lamp, and the button just stayed there floating in mid-air. Repeaters don't work, and redstone blocks do not give out a signal to redstone. Also pistons don't work, and when I place pistons the immediately face downwards. Please tell me how to fix this problem.

**Comment by turt2live** [comment]
This is due to #116.

Glowstone is not currently complete. We are working hard to get Glowstone to a fully functional server implementation, but right now there are various unimplemented features.

Many of the features we current have can be found [here](https://github.com/GlowstoneMC/Glowstone/wiki/Current-Features)
