### ISSUE TITLE
Fires don't work

### ISSUE THREAD

**Issue by yannouli** [GlowstoneMC/Glowstone-Legacy#509]
I can't light fires anywhere, or even use it on netherrack. It simply just does not work. Please tell me how to fix this issue.

**Comment by turt2live** [comment]
This is due to #325.

Glowstone is not currently complete. We are working hard to get Glowstone to a fully functional server implementation, but right now there are various unimplemented features.

Many of the features we current have can be found [here](https://github.com/GlowstoneMC/Glowstone/wiki/Current-Features)
