### ISSUE TITLE
Tnt won't light, and compliments. 

### ISSUE THREAD

**Issue by EpicRainbow** [GlowstoneMC/Glowstone-Legacy#537]
I'm new to Glowstone and for just kicking off from a couple months ago with large progress I'm pretty impressed. (I know it's been around for alot longer than that)

I noticed that tnt will not light with flint or steel. It also won't light with redstone torches, or lever. I have tried 1. Removing all plugins. 2. changing gamemodes. 
Neither fix the problem. 

I know this is a bad way to test performance but it was all I could do since it's late at night right now. It handled 27,624,240 block changes in WorldEdit without crashing on a home hosted server! I'm very impressed. Compliments to whoever figured out how to optimize that the best way. 

As you can see I'm obviously no developer or someone that works with code.

**Comment by turt2live** [comment]
TNT: #330 and #325 
Redstone: #116 

Glowstone is currently not fully complete. There are many things that have not been implemented yet.

Glad to see that your server lived after that. To be honest, it's in part due to the fact that Glowstone is not fully complete. We're trying to keep it as lightweight as you discovered, but that's getting harder as we progress.

Thanks for the report, but unfortunately it's a duplicate of the mentioned issues, so I have to close it.
