### ISSUE TITLE
PlotMe Plugin not working (at least for me)

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone-Legacy#614]
I have multiverse-core installed, plus PlotMe-Core, PlotMe-DefaultGenerator, and DynapPlotMe installed. I used the command while on a client device : <blockquote>/mv create plotworld normal -g PlotMe</blockquote> and it gave me a normal world. Can someone please resolve this as I would love to test out the rest of this plugin. I saw on the list of plugins that someone had no issues using the PlotMe plugin.
<br>
_Note that I am testing the server on a IBM ThinkPad-R51e with about 700mb of RAM runing Lubuntu 14.04_
_Running client on HP Pavilion 13_

**Comment by turt2live** [comment]
I tested this with the following plugin versions and Glowstone build number as follows:
- PlotMe 0.15.2
- PlotMe-DefaultGenerator 0.15.2
- Multiverse-Core 2.5-b678
- Glowstone `1.8-162-g6c39649-b119` 

I noticed that the command supplied failed to execute (unknown generator), but I used this command to create a plot world:

`/mv create plotworld normal -g PlotMe-DefaultGenerator`

The world generated just fine with no major applicable problems. 

**Note:**
I do recommend the use of our [IRC channel](http://webchat.esper.net/?nick=GS...&channels=glowstone&prompt=1) or our [forums](http://forums.glowstone.net) for support instead of GitHub.

**Comment by ghost** [comment]
Thank you for the support, I'll look into the forums for future support

**Comment by gdude2002** [comment]
Has your issue been solved?

**Comment by SpaceManiac** [comment]
Forum thread: [here](https://forums.glowstone.net/t/plotme-support-returns-plotme-after-every-command/120).
Should be fixed in 3848233dee8b7d7d02fcd91e08b9b8b769573065.
